# Custom window rules

# WoW / Battle.net on workspace 10
windowrule = workspace 10 silent, match:class ^(steam_app_default)$, match:title ^(Battle\.net)$
windowrule = workspace 10 silent, match:class ^(steam_app_default)$, match:title ^$
windowrule = workspace 10 silent, match:class ^(steam_app_default)$, match:title ^(World of Warcraft)$
windowrule = fullscreen 1, match:class ^(steam_app_default)$, match:title ^(World of Warcraft)$


# Scratchpad windows - always floating
windowrule = float yes, match:class ^(kitty-dropterm)$
windowrule = float yes, match:class ^(spotify)$
windowrule = float yes, match:class ^(Armagetron Advanced)$
windowrule = float yes, match:class ^(kitty-anime)$
