# Custom window rules

# Scratchpad windows - always floating
windowrule = float yes, match:class ^(kitty-dropterm)$
windowrule = float yes, match:class ^(spotify)$
windowrule = float yes, match:class ^(Armagetron Advanced)$
