
$background = rgba(1a1111ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(382e2dff)

$inverse_primary = rgba(904a4aff)

$inverse_surface = rgba(f0deddff)

$on_background = rgba(f0deddff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(561d1fff)

$on_primary_container = rgba(ffdad8ff)

$on_primary_fixed = rgba(3b080cff)

$on_primary_fixed_variant = rgba(733334ff)

$on_secondary = rgba(442929ff)

$on_secondary_container = rgba(ffdad8ff)

$on_secondary_fixed = rgba(2c1515ff)

$on_secondary_fixed_variant = rgba(5d3f3fff)

$on_surface = rgba(f0deddff)

$on_surface_variant = rgba(d7c1c0ff)

$on_tertiary = rgba(412d05ff)

$on_tertiary_container = rgba(ffdeacff)

$on_tertiary_fixed = rgba(281900ff)

$on_tertiary_fixed_variant = rgba(5a4319ff)

$outline = rgba(a08c8bff)

$outline_variant = rgba(524343ff)

$primary = rgba(ffb3b2ff)

$primary_container = rgba(733334ff)

$primary_fixed = rgba(ffdad8ff)

$primary_fixed_dim = rgba(ffb3b2ff)

$scrim = rgba(000000ff)

$secondary = rgba(e6bdbbff)

$secondary_container = rgba(5d3f3fff)

$secondary_fixed = rgba(ffdad8ff)

$secondary_fixed_dim = rgba(e6bdbbff)

$shadow = rgba(000000ff)

$source_color = rgba(df686aff)

$surface = rgba(1a1111ff)

$surface_bright = rgba(423736ff)

$surface_container = rgba(271d1dff)

$surface_container_high = rgba(322827ff)

$surface_container_highest = rgba(3d3232ff)

$surface_container_low = rgba(231919ff)

$surface_container_lowest = rgba(140c0cff)

$surface_dim = rgba(1a1111ff)

$surface_tint = rgba(ffb3b2ff)

$surface_variant = rgba(524343ff)

$tertiary = rgba(e4c18dff)

$tertiary_container = rgba(5a4319ff)

$tertiary_fixed = rgba(ffdeacff)

$tertiary_fixed_dim = rgba(e4c18dff)



$background_raw = 1a1111

$error_raw = ffb4ab

$error_container_raw = 93000a

$inverse_on_surface_raw = 382e2d

$inverse_primary_raw = 904a4a

$inverse_surface_raw = f0dedd

$on_background_raw = f0dedd

$on_error_raw = 690005

$on_error_container_raw = ffdad6

$on_primary_raw = 561d1f

$on_primary_container_raw = ffdad8

$on_primary_fixed_raw = 3b080c

$on_primary_fixed_variant_raw = 733334

$on_secondary_raw = 442929

$on_secondary_container_raw = ffdad8

$on_secondary_fixed_raw = 2c1515

$on_secondary_fixed_variant_raw = 5d3f3f

$on_surface_raw = f0dedd

$on_surface_variant_raw = d7c1c0

$on_tertiary_raw = 412d05

$on_tertiary_container_raw = ffdeac

$on_tertiary_fixed_raw = 281900

$on_tertiary_fixed_variant_raw = 5a4319

$outline_raw = a08c8b

$outline_variant_raw = 524343

$primary_raw = ffb3b2

$primary_container_raw = 733334

$primary_fixed_raw = ffdad8

$primary_fixed_dim_raw = ffb3b2

$scrim_raw = 000000

$secondary_raw = e6bdbb

$secondary_container_raw = 5d3f3f

$secondary_fixed_raw = ffdad8

$secondary_fixed_dim_raw = e6bdbb

$shadow_raw = 000000

$source_color_raw = df686a

$surface_raw = 1a1111

$surface_bright_raw = 423736

$surface_container_raw = 271d1d

$surface_container_high_raw = 322827

$surface_container_highest_raw = 3d3232

$surface_container_low_raw = 231919

$surface_container_lowest_raw = 140c0c

$surface_dim_raw = 1a1111

$surface_tint_raw = ffb3b2

$surface_variant_raw = 524343

$tertiary_raw = e4c18d

$tertiary_container_raw = 5a4319

$tertiary_fixed_raw = ffdeac

$tertiary_fixed_dim_raw = e4c18d
